More runMcV fixes. [2661]

diff --git a/release/runMcV-HeapDumpEnabled b/release/runMcV-HeapDumpEnabled
--- a/release/runMcV-HeapDumpEnabled
+++ b/release/runMcV-HeapDumpEnabled
@@ -1,5 +1,37 @@
 #!/bin/bash
 
+# _file "path" : print the file of a path.
+function _file(){
+    printf '%s' "${1##*/}"
+}
+
+# _cd "path" : change the directory of a path.
+function _cd(){
+    cd "$(printf '%s' "${1%/*}")" 2>/dev/null
+}
+
+# get_realpath "path" : echo the realpath as logical or physical.
+function get_realpath(){
+    # 0 : Good.
+    # 1 : Fail : no file/symlink broken/not regular file errors.
+    # 2 : Fail : unspecified physical file path construction error.
+    # 3 : Fail : unspecified logical or physical directory construction error. 
+    [[ ! -f "$1" ]] && return 1 # Code 1.
+    if [[ -z "$no_symlinks" ]]
+    then
+        local _pwd='pwd'
+    else
+        local _pwd='pwd -P'
+        if [[ -L "$1" ]]
+        then
+            local _ls="$( ls -dl "$1" 2>/dev/null )" &&
+            local _link="$( printf '%s' "${_ls#*"${1} -> "}" )" &&
+            echo "$( _cd "$1"; _cd "$_link" && $_pwd )"/"$(_file "$_link")" && return 0 || return 2 # Code 2.
+        fi
+    fi
+    echo "$( _cd "$1"; $_pwd )"/"$(_file "$1")" && return 0 || return 3 # Code 3.
+}
+
 MCV_PARAMS="$@"
 
 DOCUMENT_DIRECTORY="${HOME}"
@@ -8,8 +40,6 @@ if [ `uname -s` = "Darwin" ]; then
 fi
 
 MCV_USERPATH="${DOCUMENT_DIRECTORY}/McIDAS-V"
-
-MCV_JAR=$(find . -maxdepth 1 -name "mcidasv*.jar" -print)
 
 # Check for -userpath parameter
 while [ "$1" != "" ]; do
@@ -31,17 +61,22 @@ if [ -d "${HOME}/.mcidasv" ]; then
 fi
 
 # Change to the directory that the script resides in before executing
-HAVEWHICH=`which which >/dev/null 2>&1`
-if [ $? -eq 0 ]; then
-  scriptname=`which "$0" 2>/dev/null`
-else
-  scriptname="$0"
-fi
-if [ -z "${scriptname}" ]; then
-  scriptname="$0"
-fi
-dirname=`dirname "$scriptname"`
-cd "$dirname"
+#HAVEWHICH=`which which >/dev/null 2>&1`
+#if [ $? -eq 0 ]; then
+#  scriptname=`which "$0" 2>/dev/null`
+#else
+#  scriptname="$0"
+#fi
+#if [ -z "${scriptname}" ]; then
+#  scriptname="$0"
+#fi
+
+scriptname=$(get_realpath "$0")
+dirname=$(dirname "$scriptname")
+
+cd "$dirname/lib"
+
+MCV_JAR=$(find . -maxdepth 1 -name "mcidasv*.jar" -print)
 
 # Default heap size to use if none can be determined
 HEAP_DEFAULT="512M"
@@ -60,11 +95,11 @@ MCV_LOG="${MCV_USERPATH}/mcidasv.log"
 MCV_LOG_LINES="10000"
 
 # Always run the default prefs; user can override as much as they want
-if [ ! -f ./runMcV.prefs ]; then
+if [ ! -f "$dirname/runMcV.prefs" ]; then
   echo "This script must be run from within the McIDAS-V installation directory"
   exit 1
 else
-  . ./runMcV.prefs
+  . "$dirname/runMcV.prefs"
 fi
 
 # Create MCV_USERPATH directory if it doesn't already exist
@@ -77,7 +112,7 @@ fi
 
 # Copy prefs to MCV_USERPATH directory if it doesn't already exist
 if [ ! -f "${MCV_USERPATH}/runMcV.prefs" ]; then
-  cp runMcV.prefs "${MCV_USERPATH}/runMcV.prefs"
+  cp "$dirname/runMcV.prefs" "${MCV_USERPATH}/runMcV.prefs"
 fi
 
 # If MCV_USERPATH/runMcV.prefs exists, source it to populate the current environment
@@ -104,13 +139,13 @@ fi
 
 # Force Java 6 on OS X (for now).
 if [ `uname -s` = "Darwin" ]; then
-  JAVA_HOME=`/usr/libexec/java_home -v 1.6`
+  JAVA_HOME=`/usr/libexec/java_home -v 1.8`
 fi
 
 # Look for java
 JAVA_BIN="java"
-if [ -f "./jre/bin/java" ]; then
-  JAVA_BIN="./jre/bin/java"
+if [ -f "$dirname/jre/bin/java" ]; then
+  JAVA_BIN="$dirname/jre/bin/java"
 else
   if [ -n "${JAVA_HOME}" ]; then
     JAVA_BIN="${JAVA_HOME}/bin/java"
